### ISSUE TITLE
Use Hydra as background of Troop

### ISSUE THREAD

**Issue by KonVas** [ojack/hydra-sync#1]
Hello, I am trying to set up hydra as background to Troop, it is a collective coding env that runs as python app. So I am running hydra in a local network and I have also installed the screen sharing extension from Chrome, but there is no information on how to make hydra as background in the repo or elsewhere.

**Comment by ojack** [comment]
Hi, this is outside the scope of what Hydra does. You should ask in the Troop repository, or feel free to ask in the hydra forum to see if anyone has tried to do something similar :) https://talk.lurk.org/channel/hydra
